language: android
sudo: false
jdk: oraclejdk8
dist : trusty
env:
  global:
    - ANDROID_API=25
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=25.0.2
    - ADB_INSTALL_TIMEOUT=5
    - TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - openssl aes-256-cbc -K $encrypted_e106cbe777cb_key -iv $encrypted_e106cbe777cb_iv -in treehouses-remote.jks.enc -out treehouses-remote.jks -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - chmod +x gradlew - yes | sdkmanager "platforms;android-28"
  - "./gradlew dependencies || true"
install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
    - build-tools-23.0.1
    - android-24
    - android-23
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
after_success:	
  - sh set_tags.sh
before_deploy:
  - cp $TRAVIS_BUILD_DIR/treehouses-remote.jks $HOME
  - cd app/build/outputs/apk/release
  - ls
  - cp remote-$TRAVIS_BUILD_NUMBER.apk remote-unaligned.apk
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/treehouses-remote.jks -storepass $key_store_password -keypass $keystore_alias_password remote-unaligned.apk treehouses
  - jarsigner -verify remote-unaligned.apk
  - "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 remote-unaligned.apk remote.apk"
  - sha256sum remote.apk > remote.apk.sha256
  - rm remote-unaligned.apk
  - ls
deploy:
  provider: releases
  api_key:
    secure: F9Rs4BPHf1+O0paanM+I6+3b8NIwUZXvKiT8+SmLAHHXpxkIBYJwKlPROrLyYWKgl2LLpEgU4kZrDo8SORLucwN4kfF5RpyQahcd8eh9db9jdY+Rxad3vbwk3g2X+RNtlb7Y3b0ttaxzWHbCBH+B4stEQzv1rY5X5uS1HeOUW3ekEsqcIhQ3P14MIaNI99P12ycdePx6LAUQnqfEqvIrKgth4maYUGBtKyx9eAlxbMr3qBsXaCpDgqnRImwr+4EYnto+4U9iFc0z+cFa4y4axpi9tl21p4ufaEzy32a7AD3BGlhXaT4sznrjvoxIV9DGKuTczNEqECPNspC8rfJbGbvpHB44CA0jCZxlGo3y5bBFf4PdsxihG1d7SdD9JErWfx0qierj4ueXkdiGZxPO6fMX9o+1TETrR0QnvrD5JIDJggKWVuAr2E2ZybJdO+pFQKA++mxgYjyRaS4otQgc3a/q5ulfwVvEBys7MyIa310vK8X+sbSSp4kcjZTflSaohgczOMc3WAxJRykf0i/S1x8t5SoIrUQ560fj3KF40SPRIzHMQizTFVmA/9W7qEoTPGVkIKlJmmK7D1WEMn0WNHDW9HVeIqRNcEhuOJ0bYST+FYUVPgqvtcDDR8lNMZZMG+gm8nXUfX0E/sfSqP7qrqVhXc5ty5iQfQPSliBL/lE=
  file_glob: true
  file: ./*
  skip-cleanup: true
  on:
    repo: treehouses/remote
    branch: master
notifications:
  email: false
