name: build check

on:
  push:
    branches:
      - '*'
      - '!master'
#  workflow_dispatch:
#    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
      - name: build
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
